server:
  port: 8761
#http://localhost:8761/

spring:
  application:
    name: NAMING-SERVER

##to prevent eureka server from registering itself
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
